### ISSUE TITLE
群组申请收录

### ISSUE THREAD

**Issue by Dom-X** [alexbei/telegram-groups#10]
亿万同人字幕组tg群：https://t.me/ywtrzm
群内会同步更新字幕组译制的影视作品，以及部分在tg首发的作品。亿万字幕组涉及的lgbtq影视范围广，语种多，小语种影片层出不穷。组中各类语种翻译制作小组翻译的作品包括韩语、法语、德语、意大利语、西班牙语、葡萄牙语、丹麦语、冰岛语等等，翻译过各大电影节的热门影片。

酷漫404字幕组tg群：https://t.me/CoolComic404_Fans
酷漫字幕组涉及漫威+DC+日漫番剧等方面，还有更多独家译制的特效字幕。群内会同步更新字幕组译制的影视作品。

**Comment by alexbei** [comment]
已收录
