### ISSUE TITLE
机器人收录申请

### ISSUE THREAD

**Issue by jw-star** [alexbei/telegram-groups#11]
**频道、群组或机器人的链接**
https://t.me/DouYintg_bot

**频道、群组或机器人的简介**
抖音，tiktok 视频图文解析，推特、ins、youtube解析，长期维护

**Comment by alexbei** [comment]
怎么用的，请给个示例。

**Comment by jw-star** [comment]
![image](https://github.com/alexbei/telegram-groups/assets/48782751/12e553d0-c6f8-47e6-9cc8-612b720d5189)

**Comment by jw-star** [comment]
> 怎么用的，请给个示例。

看到列表里已经有一个了，但是失效了似乎，我提交了一个

**Comment by jw-star** [comment]
![image](https://github.com/alexbei/telegram-groups/assets/48782751/d0bb931c-03be-4e64-bc9a-3a5d775fab21)

**Comment by alexbei** [comment]
哪个失效了

**Comment by jw-star** [comment]
X.cat	视频音频图片GIF下载，YouTube/Tumblr/推特/ins/微信/快手/抖音/QQ音乐等

**Comment by alexbei** [comment]
https://t.me/DouYintg_bot 已收录
X.cat 已处理

**Comment by alexbei** [comment]
![image](https://github.com/alexbei/telegram-groups/assets/83709912/1e9c0a43-fa0b-4db3-9e67-8cd0de7d9c04)
有推广VPN的，暂不收录

**Comment by jw-star** [comment]
好吧，那算了
