### ISSUE TITLE
频道申请收录

### ISSUE THREAD

**Issue by ripaojiedian** [alexbei/telegram-groups#6]
免费翻墙订阅，破解VPN
破解软件，白嫖资源分享
https://t.me/ripaojiedian
免费机场订阅、圈X破解脚本
苹果破解应用、安卓破解应用
https://t.me/helloworld_1024
伟人原创Quantumultx脚本频道。
https://t.me/WeiRenQAQ

**Comment by alexbei** [comment]
科学上网相关的暂不收录
