### ISSUE TITLE
申请2个频道收录

### ISSUE THREAD

**Issue by dmcdark** [alexbei/telegram-groups#7]
https://t.me/TelBaptist
一直没有找到好的基督讲道资源频道，我就自己了建一个，请多支持！
(ง •̀_•́)ง
2020-03-26

https://t.me/info404
分享404信息，有新闻、猫猫狗狗搞笑图、梗图，偶尔有限免游戏、漂亮的风景、视频等等。
没有广告，不插播广告。
免责声明：
不知真假，自行判断，
吃瓜群众，不要较真。

**Comment by alexbei** [comment]
https://t.me/info404 人数太少
https://t.me/TelBaptist 宗教相关的不收录
