### ISSUE TITLE
频道推荐收录

### ISSUE THREAD

**Issue by at2008** [alexbei/telegram-groups#8]
[科技&趣闻&杂记](https://t.me/kejiqu)
[https://t.me/kejiqu](https://t.me/kejiqu)
分享有价值、有趣的信息！前沿科技资讯，娱乐、影视新闻，以及世间趣闻。。。

[网盘资源收藏(夸克)](https://t.me/yunpanshare)
[https://t.me/yunpanshare](https://t.me/yunpanshare)
夸克云盘 软件工具 教程 影音 资源分享

**Comment by alexbei** [comment]
已收录
